-- Sprint 2: CodeForge AI usage and per-user limits.
-- Run this migration in the Supabase SQL editor.

create table if not exists public.ai_usage (
    id bigint generated by default as identity primary key,
    request_id uuid not null unique,
    user_id uuid not null references auth.users(id) on delete cascade,
    project_id uuid not null references public.projects(id) on delete cascade,
    model text not null,
    task text not null default 'coding',
    status text not null check (status in ('started', 'success', 'error', 'cancelled')),
    input_tokens bigint not null default 0,
    output_tokens bigint not null default 0,
    total_tokens bigint not null default 0,
    duration_ms bigint not null default 0,
    error_code text,
    created_at timestamptz not null default now()
);

create index if not exists ai_usage_user_created_idx
    on public.ai_usage(user_id, created_at desc);

create index if not exists ai_usage_project_created_idx
    on public.ai_usage(project_id, created_at desc);

create table if not exists public.ai_limits (
    user_id uuid primary key references auth.users(id) on delete cascade,
    daily_request_limit integer not null default 100 check (daily_request_limit >= 0),
    daily_token_limit bigint not null default 0 check (daily_token_limit >= 0),
    updated_at timestamptz not null default now()
);

alter table public.ai_usage enable row level security;
alter table public.ai_limits enable row level security;

-- Service-role access is used by the FastAPI backend. These policies also allow
-- authenticated users to inspect only their own telemetry through Supabase.
drop policy if exists "users can read own ai usage" on public.ai_usage;
create policy "users can read own ai usage"
    on public.ai_usage for select
    to authenticated
    using (auth.uid() = user_id);

drop policy if exists "users can read own ai limits" on public.ai_limits;
create policy "users can read own ai limits"
    on public.ai_limits for select
    to authenticated
    using (auth.uid() = user_id);
